---
title: "figure"
author: "zhuofan"
date: '2022-11-14'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(robCompositions)
datafamily <- read.csv("/Users/wangzhuofan/Project/coalescence/realdata/Family.csv",header = FALSE)
ds <- as.character(datafamily[1,-1])
rownames(datafamily) <- c("",datafamily$V1[-1])
colnames(datafamily) <- c("",ds)
datafamily <- datafamily[-1,-1]
metadata <- read.csv("/Users/wangzhuofan/Project/coalescence/realdata/metadata.csv")
ns <- metadata$Sample
ns_oral <- ns[metadata$Material=="Oral"]
ns_stool <- ns[metadata$Material=="Stool"]
meta_oral <- subset(metadata,Material=="Oral")
meta_stool <- subset(metadata,Material=="Stool")
pairsm <- data.frame(oral=ns_oral,stool=NA)
templ <- list()
for (i in 1:768) {
  pairsm$oral[i] <- ns_oral[i]
  temp <- which((meta_stool$Patient==metadata$Patient[i])&(meta_stool$Timepoint==metadata$Timepoint[i]))
  templ[[i]] <- temp
  if(length(temp)==1){
    pairsm$stool[i] <- ns_stool[temp]
  }
  if(length(temp)==2){
    pairsm$stool[i] <- ns_stool[min(temp)]
  }
}
pairsm <- na.omit(pairsm)
pairs_record <- pairsm
pairs_record$oral <- match(pairsm$oral,ds)
pairs_record$stool <- match(pairsm$stool,ds)
pairs_record <- na.omit(pairs_record)
#oral_index <- na.omit(match(pairsm$oral,ds))
#stool_index <- na.omit(match(pairsm$stool,ds))
family_oral <- datafamily[,pairs_record$oral]
family_stool <- datafamily[,pairs_record$stool]
ratio0 <- data.frame(oral=apply(family_oral,1,function(x){sum(x==0)/ncol(family_oral)}),stool=apply(family_stool,1,function(x){sum(x==0)/ncol(family_stool)}))
library(dplyr)
select_ratio <- which(ratio0$oral<0.9&ratio0$stool<0.9)
family_oral <- family_oral[select_ratio,]
family_stool <- family_stool[select_ratio,]
oral_mat <- matrix(as.numeric(as.matrix(family_oral)),nrow = 20)
stool_mat <- matrix(as.numeric(as.matrix(family_stool)),nrow = 20)
imp_oral <- as.matrix(impRZilr(t(oral_mat))$x)
imp_stool <- as.matrix(impRZilr(t(stool_mat))$x)
oral_scale <- t((imp_oral)/rowSums(imp_oral))
stool_scale <- t((imp_stool)/rowSums(imp_stool))
heatmap(t(oral_scale),Rowv = NA, Colv = NA)
heatmap(t(stool_scale),Rowv = NA, Colv = NA)
# dd_data <- list(n = 515, px = 20, py = 20, x = stool_scale, y = oral_scale)
# dd_data <- list(n = 515, px = 20, py = 20, x = oral_scale, y = stool_scale)
# model_dd = stan_model('coalescencezhuofan.stan')
# fit = sampling(model_dd,dd_data,iter=2000,chains=4,cores = parallel::detectCores())
# # heatmap(x,Rowv = NA, Colv = NA)
# # heatmap(y,Rowv = NA, Colv = NA)
# params = extract(fit)
# sam_mest <- apply(params$mt,c(2,3),mean)
# heatmap(t(sam_mest), Rowv = NA, Colv = NA)
heatmap(t(x), Rowv = NA, Colv = NA)
# heatmap(t(oral_scale),Rowv = NA, Colv = NA)
heatmap(t(y), Rowv = NA, Colv = NA)
```
```{r}
par(mfrow=c(3,3))
for(i in 1:14) 
  for(j in 1:7)
    plot(stool_mat[j,],oral_mat[i,])

```